# Generated by Django 5.2.4 on 2025-07-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPrincipal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpeta',
            name='created_at',
        ),
        migrations.AddField(
            model_name='carpeta',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
