# Generated by Django 5.2.4 on 2025-07-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPrincipal', '0002_remove_carpeta_created_at_carpeta_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpeta',
            name='publica',
            field=models.BooleanField(default=False),
        ),
    ]
