# Generated by Django 5.2.4 on 2025-07-16 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPrincipal', '0004_archivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='subido_por',
        ),
        migrations.AddField(
            model_name='archivo',
            name='nombre',
            field=models.CharField(default='Archivo sin nombre', max_length=200),
        ),
        migrations.AddField(
            model_name='archivo',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='carpeta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='AppPrincipal.carpeta'),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='descripcion',
            field=models.CharField(default='Archivo sin nombre', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='nombre',
            field=models.CharField(default='Archivo sin nombre', max_length=100),
        ),
    ]
