# Generated by Django 4.2.7 on 2025-07-18 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppPrincipal', '0005_remove_archivo_subido_por_archivo_nombre_and_more'),
    ]

    operations = [
        # Crear modelo PeriodoAcademico
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del período')),
                ('periodo', models.CharField(choices=[('1', 'Primer Período'), ('2', 'Segundo Período')], max_length=1, verbose_name='Período')),
                ('año', models.IntegerField(verbose_name='Año')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('activo', models.BooleanField(default=False, verbose_name='Período activo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Período Académico',
                'verbose_name_plural': 'Períodos Académicos',
                'ordering': ['-año', '-periodo'],
            },
        ),
        
        # Agregar campos a Carpeta
        migrations.AddField(
            model_name='carpeta',
            name='periodo_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carpetas', to='AppPrincipal.periodoacademico', verbose_name='Período académico'),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='carpeta_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcarpetas', to='AppPrincipal.carpeta', verbose_name='Carpeta padre'),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='tipo_carpeta',
            field=models.CharField(choices=[('horario_general', 'Horario General'), ('carga_horaria', 'Carga Horaria'), ('mallas_curriculares', 'Mallas Curriculares'), ('peas_revision', 'PEAs para Revisión'), ('planificacion_academica', 'Planificación Académica'), ('informacion_carrera', 'Información de la Carrera'), ('pea_legalizados', 'PEA Legalizados'), ('informes_academicos', 'Informes Académicos'), ('horarios_legalizados', 'Horarios Legalizados'), ('personalizada', 'Personalizada')], default='personalizada', max_length=50, verbose_name='Tipo de carpeta'),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='orden',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        
        # Agregar índices únicos
        migrations.AddConstraint(
            model_name='periodoacademico',
            constraint=models.UniqueConstraint(fields=['año', 'periodo'], name='unique_periodo_año'),
        ),
    ]
