# Generated by Django 4.2.7 on 2025-07-18 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppPrincipal', '0006_auto_20250717_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoActivoPorUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seleccion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Período Activo por Usuario',
                'verbose_name_plural': 'Períodos Activos por Usuario',
            },
        ),
        migrations.AlterModelOptions(
            name='carpeta',
            options={'ordering': ['orden', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='periodoacademico',
            options={'ordering': ['-año', '-periodo']},
        ),
        migrations.RemoveConstraint(
            model_name='periodoacademico',
            name='unique_periodo_año',
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='carpeta_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcarpetas', to='AppPrincipal.carpeta'),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='periodo_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPrincipal.periodoacademico'),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='tipo_carpeta',
            field=models.CharField(choices=[('horario_general', '1. HORARIO GENERAL'), ('carga_horaria', '2. CARGA HORARIA'), ('mallas_curriculares', '3. MALLAS CURRICULARES'), ('peas_revision', '4. PEAS PARA REVISIÓN'), ('planificacion_academica', '5. PLANIFICACION ACADEMICA'), ('informacion_carrera', '6. INFORMACIÓN DE LA CARRERA'), ('pea_legalizados', '7. PEA LEGALIZADOS'), ('informes_academicos', '8. INFORMES ACADEMICOS'), ('horarios_legalizados', '9. HORARIOS LEGALIZADOS'), ('personalizada', 'Carpeta Personalizada')], default='personalizada', max_length=30),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='año',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='periodo',
            field=models.CharField(choices=[('1', 'Período 1'), ('2', 'Período 2')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='periodoacademico',
            unique_together={('periodo', 'año')},
        ),
        migrations.AddField(
            model_name='periodoactivoporusuario',
            name='periodo_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPrincipal.periodoacademico'),
        ),
        migrations.AddField(
            model_name='periodoactivoporusuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='periodo_activo_personal', to=settings.AUTH_USER_MODEL),
        ),
    ]
