# Generated by Django 4.2.7 on 2025-07-18 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppPrincipal', '0007_periodoactivoporusuario_alter_carpeta_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAdministrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vinculacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administradores_vinculados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'administrador')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='periodoacademico',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='periodoacademico',
            name='administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='periodoacademico',
            unique_together={('periodo', 'año', 'administrador')},
        ),
        migrations.DeleteModel(
            name='PeriodoActivoPorUsuario',
        ),
    ]
